//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductData
{

    public partial class ProductOption
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
